[package]
name = "Reclaimer"
version = "0.1.0"
edition = "2024"

[package.metadata.bundle]
name = "Reclaimer"
identifier = "com.dincertekin.reclaimer"
icon = ["icons/icon.png"]

[dependencies]
eframe = { version = "0.34.3", features = ["persistence"] }
egui  = "0.34.3"
rfd   = "0.15"
open  = "5"
image = { version = "0.25", default-features = false, features = ["png"] }
